var bp_comm = {
    funnelSearchName : [
        {id:'user_id',text:'用户ID'},
        {id:'user_name',text:'用户名'},
        // {id:'',text:'国家'},
        // {id:'',text:'省份'},
        // {id:'',text:'城市'},
        // {id:'',text:'设备类型'},
        // {id:'',text:'设备品牌'},
        // {id:'',text:'设备名称'},
        // {id:'',text:'操作系统名称'},
        // {id:'',text:'操作系统版本'},
        // {id:'',text:'浏览器内核'},
        // {id:'',text:'浏览器名称'},
        // {id:'',text:'浏览器版本'},
        // {id:'',text:'屏幕分辨率'},
        // {id:'',text:'屏幕宽度'},
        // {id:'',text:'屏幕高度'},
        // {id:'',text:'插件'},
        // {id:'',text:'联网方式'},
        // {id:'',text:'语言'},
        // {id:'',text:'运营商'},
        {id:'register_channel_id',text:'注册渠道ID'},
        {id:'register_channel_name',text:'注册渠道名称'},
        // {id:'',text:'访问渠道ID'},
        // {id:'',text:'访问渠道ID'},
        {id:'register_time',text:'注册时间'},
        {id:'login_last_time',text:'登陆时间'},
        // {id:'',text:'退出时间'},
        {id:'order_last_time',text:'下单时间'},
        {id:'pay_begin_time',text:'支付时间'},
        {id:'pay_last_time',text:'支付完成时间'},
        // {id:'',text:'首次下单时间'},
        // {id:'',text:'访问页面'},
        // {id:'',text:'访问页面时间'},
        // {id:'',text:'页面按钮点击次数'},
        // {id:'',text:'页面按钮点击时间'},
        // {id:'',text:'访客用户'},
        // {id:'',text:'注册用户'},
        // {id:'',text:'代理用户'},
	],
	funnelSearchOpt : [
        {id:'equals',text:'等于'},
        {id:'!=',text:'不等于'},
        {id:'like',text:'包含'},
        {id:'not like',text:'不包含'},
        {id:'is not null',text:'有值'},
        {id:'is null',text:'没值'},
        // {id:'',text:'为空'},
        // {id:'',text:'不为空'},
        {id:'regexp',text:'正则匹配'},
        {id:'not regexp',text:'正则不匹配'},
	]
}